name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: https://git.akagiyui.com/actions/checkout@v4

      - name: Cache PlatformIO and Pip Cache
        uses: https://git.akagiyui.com/actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ~/.platformio/packages
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: https://git.akagiyui.com/actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: |
          pip install -i https://pypi.registry.akagiyui.com/root/pypi/+simple --upgrade platformio
          pio system info
          ##python3 ./replace_pio_registry_mirror.py

      - name: Build PlatformIO Project
        run: |
          pio run
          pio run --target buildfs

      - name: Upload Firmware Binaries
        uses: https://git.akagiyui.com/actions/gitea-upload-artifact@v4
        with:
          name: bin
          path: |
            .pio/build/esp32-s3-devkitc-1/*.bin
