name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: https://git.akagiyui.com/actions/checkout@v4

      - uses: https://git.akagiyui.com/actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: https://git.akagiyui.com/actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install -i https://pypi.registry.akagiyui.com/root/pypi/+simple --upgrade platformio

      - name: Build PlatformIO Project
        run: |
          pio run
          pio run --target buildfs

      - uses: https://git.akagiyui.com/actions/upload-artifact@v4
        with:
          name: bin
          path: |
            .pio/build/esp32-s3-devkitc-1/*.bin
