name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: |
          pio run
          pio run --target buildfs

      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: |
            .pio\build\esp32-s3-devkitc-1\bootloader.bin
            .pio\build\esp32-s3-devkitc-1\firmware.bin
            .pio\build\esp32-s3-devkitc-1\littlefs.bin
